### ISSUE TITLE
Is this project dead or in need of additional contributors?

### ISSUE THREAD

**Issue by stdavis** [gharlan/alfred-github-workflow#124]
@gharlan,

I absolutely love this project! I use it many, many times per day. It's one of those things that just makes my workday go a little more smoothly. Thanks!

It appears that this project hasn't had any meaningful contributions for several years. There's a handful of open PR's that look like they would be great if they were merged.

Are you open to adding additional contributors to this project to help it stay healthy? I don't have a ton of extra time, but I would be interested in helping where I can. I'm not a PHP expert but I'm sure that I could help move things forward. I'm guessing that there are others that would be happy to help as well.

---

Everyone else,

If @gharlan isn't able to respond for some reason, are there any others out there that would be interested in collaborating with me on a rewrite of this workflow in JavaScript? I've used [alfy](https://github.com/sindresorhus/alfy) on a few other workflows before and I feel like we could get something going fairly quickly.

**Comment by gharlan** [comment]
Hi @stdavis,
Thanks for asking! The project is not dead, I'm using it myself every day. But I mainly use it to jump to the repository main page, I rarely use the sub commands. Since my main purpose is working well for me, I have been very inactive here the last few years.

But I take your issue as an opportunity to become more active in responding/reviewing/merging pull requests here.
At the moment I will not add other maintainers here, but I'll keep considering it.

**Comment by stdavis** [comment]
Awesome! I saw your recent PR merge. I'm looking forward to a new release. Thanks, again, for the awesome project!
