### ISSUE TITLE
Plugin breaks after update with Alfred 3

### ISSUE THREAD

**Issue by MartijnNieuwenhuizen** [gharlan/alfred-github-workflow#125]
Unfortunately, the plugin broke after I updated this plugin. 

## Scenario
- When using `gh ` in alfred, the plugin mentions an update
- Proceed with the update
- The plugin now shows an error in the alfred settings

## Screenshot of the error
![Screenshot 2021-10-27 at 15 19 33](https://user-images.githubusercontent.com/6492909/139073919-e3466be1-eb98-478d-a4ad-6bfdad2c9a73.png)

Is it possible to keep the functionality for Alfred 3 while supporting Alfred 4?

## Versions
Alfred: v3.8.6
Plugin (doesn't say but I expect the last version due to the update)

**Comment by MartijnNieuwenhuizen** [comment]
> Why do you use Alfred 3?

I've bought this version once without the possibility to upgrade.

@alexanderyarm this fixed it for me:
- Remove the old workflow
- Download and install the latest working version from https://github.com/gharlan/alfred-github-workflow/releases/tag/v1.6.2
- Type `ga` in the alfred command bar and select `deactivate auto update`

**Comment by ebouchut** [comment]
❓Just curious, does version 1.6.2 works for someone using Alfred **3** on an **Intel** Mac?

 @MartijnNieuwenhuizen 
 ℹ️ I am using a M1 Mac and installed 1.6.2 but I'm stuck after typing `gh ` because there is no completion.
Installing php (`brew install php`) beforehand did not help.

My 2 cents guess would be that Github API may have changed since 1.6.2 which would explain why this workflow no longer works.
Maybe @gharlan would shed my light on this. 🙏🏻

**Comment by ebouchut** [comment]
I since then have upgraded to Alfred 4 from 3. 😀

**Comment by gharlan** [comment]
I do not plan to add back support for Alfred 3.
