### ISSUE TITLE
Don't recursively search for files

### ISSUE THREAD

**Issue by gustavohenke** [gharlan/alfred-github-workflow#98]
I work on a large repo and, from time to time, I want to open a file by using Alfred.

Per the lines below:
https://github.com/gharlan/alfred-github-workflow/blob/a5c0bd28d3fd472caba703e0437393059c827d17/search.php#L385-L395

As I understand, the workflow will only add results to the screen after the whole tree has been scanned.
This is either taking ages or not working at all, and will likely be [a truncated response](https://developer.github.com/v3/git/trees/#get-a-tree-recursively).

Could we perhaps have a way to disable that, so that the repo gets scanned faster?

**Comment by gharlan** [comment]
I checked it with symfony/symfony, a very big mono repository. Performance seems to be ok for me.

**Comment by gustavohenke** [comment]
Oh Symfony is cute with its ~55 MB and ~5.6K files.

Here's my use case:
https://canvatechblog.com/we-put-half-a-million-files-in-one-git-repository-heres-what-we-learned-ec734a764181

Can you reconsider my suggestion?

**Comment by gharlan** [comment]
I will not work on this myself.

---

From https://docs.github.com/en/rest/git/trees#get-a-tree:

> Note: The limit for the tree array is 100,000 entries with a maximum size of 7 MB when using the recursive parameter.

So there is already a limit. 

I checked with `torvalds/linux`. The response contains `"truncated": true`, so it seems to be bigger than the limit. 
First call of `gh torvalds/linux /` is a bit slow, but acceptable for me. Following calls are much faster, because of caching.
